services:
  mock-printer:
    build: .            # Statt ./mock-printer
    environment:
      - HOST_IP=${HOST_IP:-0.0.0.0}  # Kann über .env überschrieben werden
    ports:
      - "8551:8551"  # RTSP Port für Printer 1
      - "8552:8552"  # RTSP Port für Printer 2
      - "8553:8553"  # RTSP Port für Printer 3
      - "8554:8554"  # RTSP Port für Printer 4
      - "8991:8991/udp"  # Discovery Port
    networks:
      - printer-network

networks:
  printer-network:
    driver: bridge 