services:
  mock-printer:
    container_name: mock-printer
    build: .            # Statt ./mock-printer
    environment:
      - HOST_IP=${HOST_IP:-0.0.0.0}  # Kann über .env überschrieben werden
    ports:
      - "322:322"  # Bambulab RTSP
      - "554:554"  # Standard RTSP
      - "8883:8883"  # Bambulab
      - "9100:9100"  # Printer
      - "1900:1900/udp"  # SSDP
      - "8991:8991/udp"  # Discovery
    networks:
      - printer-network
    tty: true  # Wichtig für interaktiven Modus
    stdin_open: true  # Wichtig für interaktiven Modus

  rtsp-proxy:
    container_name: rtsp-proxy
    image: bluenviron/mediamtx
    ports:
      - "323:322"  # Proxy für Bambulab RTSP
      - "555:554"  # Proxy für Standard RTSP
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    depends_on:
      - mock-printer
    networks:
      - printer-network

networks:
  printer-network:
    driver: bridge 