name: Build Windows Installer

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Build
      run: |
        dotnet restore installer/BambuCAM.Installer
        dotnet publish installer/BambuCAM.Installer -c Release -r win-x64 --self-contained true
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./installer/BambuCAM.Installer/bin/Release/net7.0-windows/win-x64/publish/BambuCAM Setup.exe
        asset_name: BambuCAM-Setup.exe
        asset_content_type: application/vnd.microsoft.portable-executable 