name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: |
            bangertech/bambucam-frontend:latest
            bangertech/bambucam-frontend:${{ github.ref_name }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: |
            bangertech/bambucam-backend:latest
            bangertech/bambucam-backend:${{ github.ref_name }}

      - name: Create Release ZIP
        run: |
          mkdir -p release
          cp docker-compose.prod.yml release/docker-compose.yml
          cd release
          zip -r ../BambuCAM.zip *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: BambuCAM.zip 