name: Build and Release Installer

on:
  push:
    tags:
      - '*'

# Füge Permissions hinzu
permissions:
  contents: write  # Für Release-Erstellung
  packages: write  # Für Container-Registry

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build Installer
        run: |
          cd installer/BambuCAM.Installer
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: installer/BambuCAM.Installer/bin/Release/net8.0/win-x64/publish/BambuCAM.Installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 