name: Create Release and Publish Docker Image

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: bangertech/bambucam:backend-latest
          provenance: false
      
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: bangertech/bambucam:frontend-latest
          provenance: false
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Automatisches Release von BambuCAM
            
            Docker Images:
            ```bash
            # Frontend
            docker pull bangertech/bambucam:frontend-latest
            
            # Backend
            docker pull bangertech/bambucam:backend-latest
            ```
            
            Änderungen in diesem Release:
            - ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      
      - name: Create docker-compose.yml for release
        run: |
          cat > docker-compose.yml << 'EOL'
          services:
            backend:
              image: bangertech/bambucam:backend-latest
              ports:
                - "4000:4000"
                - "9000:9000"
                - "8883:8883"
                - "8884:8884"
                - "1990:1990"
                - "1991:1991"
              network_mode: "host"
              privileged: true
            
            frontend:
              image: bangertech/bambucam:frontend-latest
              ports:
                - "3000:3000"
              depends_on:
                - backend
          EOL
      
      - name: Create Release ZIP
        run: |
          zip BambuCAM-docker.zip docker-compose.yml README.md
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./BambuCAM-docker.zip
          asset_name: BambuCAM-docker.zip
          asset_content_type: application/zip 